apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: iptables-agent 
  labels:
    name: iptables-agent 
    app: iptables-agent
    version: 0.1.0
spec:
  template:
    metadata:
      labels:
        app: iptables-agent
        version: 0.1.0
    spec:
      hostNetwork: true
      containers:
      - name: gci-iptables-config-agent
        image: quay.io/samsung_cnct/gci-iptables-config-agent
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 65

